name: bump-internal-repo-and-install

on:
  push:
    branches: [master]

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          repository: grouparoo/internal
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: internal
      - name: Bump the bumpfile
        run: rm -rf .repo-bump && date > .repo-bump
      - name: NPM install
        run: npm install
      - name: Commit files
        run: |
          git config --local user.email "hello@grouparoo.com"
          git config --local user.name "Grouparoo Bot"
          git commit -m "grouparoo/grouparoo changed - Bump!" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: grouparoo/internal
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
